schema_version: 1

context:
  version: "0.1.1"

package:
  name: mutt-language-server
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mutt-language-server/mutt_language_server-${{ version }}.tar.gz
  sha256: 9e16e75eee36e748c7cf99c436c1f5444e861b24dd74763a4c7e551484fd8db2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mutt-language-server = mutt_language_server.__main__:main

requirements:
  host:
    - python =${{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >=${{ python_min }}
    - lsp-tree-sitter
    - tree-sitter-muttrc >=0.0.4

tests:
  - python:
      imports:
        - mutt_language_server
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check
      - mutt-language-server --help

about:
  summary: mutt language server
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/neomutt/mutt-language-server
  repository: https://github.com/neomutt/mutt-language-server

extra:
  recipe-maintainers:
    - danielnachun
